EXTRACT:
  ENABLE: True
  DATASET: UCFAnomalyDetection
  DATASET_SPLITS: [train, test]
  FRAMES_BATCH_SIZE: 32
  FRAMES_BATCHES_BATCH_SIZE: 64
  NUMBER_OUTPUT_SEGMENTS: 32
  VIDEOS_BATCH_SIZE: 1
  FEATURES_EXT: pt
  FORCE_REWRITE: False
BACKBONE:
  NAME: Kinetics_X3D_L
  CONFIG_FILE_PATH: backbone-configs/Kinetics/X3D_L.yaml
  CHECKPOINT_FILE_PATH: backbone-checkpoints/Kinetics/x3d_l.pyth
  FEATURE_EXTRACTION: True
  FEATURES_LENGTH: 2048
  TRAINABLE: False
  MERGE_CFG_LIST: [NUM_GPUS, BACKBONE.TRAINABLE]
DATA:
  PATH_TO_DATA_DIR: UCF_Anomaly_Detection
  READ_FEATURES: False
  USE_FILES: available
  SKIP_LARGE_VIDEOS: True
  MAX_VIDEO_SIZE: 524288000
  PATH_LABEL_SEPARATOR: " "
  PATH_LABEL_SEPARATOR_TRAINING: "/"
  PATH_LABEL_SEPARATOR_VALIDATION: " "
  PATH_LABEL_SEPARATOR_TESTING: "  "
  MEAN: [0.45, 0.45, 0.45]
  INPUT_CHANNEL_NUM: 3
  STD: [0.225, 0.225, 0.225]
  SCALES: [312, 416]
  TARGET_FPS: 30
  DECODING_BACKEND: pyav
  MULTI_LABEL: False
  ENSEMBLE_METHOD: sum
  REVERSE_INPUT_CHANNEL: False
  EXT: mp4
TRANSFORM:
  CODE: NONE
  BG_SUBTRACTION_ENABLED: False
NUM_GPUS: 4
RNG_SEED: 1
LOG_MODEL_INFO: True